# Generated by Django 2.1.2 on 2018-10-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_imagem_noticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
